# TCL File Generated by Component Editor 14.1
# Sun May 10 15:31:40 BST 2015
# DO NOT MODIFY


# 
# QEI "QEI" v1.0
#  2015.05.10.15:31:40
# 
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1


# 
# module QEI
# 
set_module_property DESCRIPTION ""
set_module_property NAME QEI
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME QEI
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL QEI
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file QEI.v VERILOG PATH QEI.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL QEI
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file QEI.v VERILOG PATH QEI.v


# 
# parameters
# 
add_parameter AUTO_CLOCK_SINK_CLOCK_RATE STRING -1
set_parameter_property AUTO_CLOCK_SINK_CLOCK_RATE DEFAULT_VALUE -1
set_parameter_property AUTO_CLOCK_SINK_CLOCK_RATE DISPLAY_NAME AUTO_CLOCK_SINK_CLOCK_RATE
set_parameter_property AUTO_CLOCK_SINK_CLOCK_RATE TYPE STRING
set_parameter_property AUTO_CLOCK_SINK_CLOCK_RATE UNITS None
set_parameter_property AUTO_CLOCK_SINK_CLOCK_RATE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_n reset_n Input 1


# 
# connection point EncoderIn
# 
add_interface EncoderIn conduit end
set_interface_property EncoderIn associatedClock ""
set_interface_property EncoderIn associatedReset ""
set_interface_property EncoderIn ENABLED true
set_interface_property EncoderIn EXPORT_OF ""
set_interface_property EncoderIn PORT_NAME_MAP ""
set_interface_property EncoderIn CMSIS_SVD_VARIABLES ""
set_interface_property EncoderIn SVD_ADDRESS_GROUP ""

add_interface_port EncoderIn encABZ encabz Input 3


# 
# connection point mms
# 
add_interface mms avalon end
set_interface_property mms addressUnits WORDS
set_interface_property mms associatedClock clock_sink
set_interface_property mms associatedReset reset_sink
set_interface_property mms bitsPerSymbol 8
set_interface_property mms burstOnBurstBoundariesOnly false
set_interface_property mms burstcountUnits WORDS
set_interface_property mms explicitAddressSpan 0
set_interface_property mms holdTime 0
set_interface_property mms linewrapBursts false
set_interface_property mms maximumPendingReadTransactions 0
set_interface_property mms maximumPendingWriteTransactions 0
set_interface_property mms readLatency 0
set_interface_property mms readWaitTime 1
set_interface_property mms setupTime 0
set_interface_property mms timingUnits Cycles
set_interface_property mms writeWaitTime 0
set_interface_property mms ENABLED true
set_interface_property mms EXPORT_OF ""
set_interface_property mms PORT_NAME_MAP ""
set_interface_property mms CMSIS_SVD_VARIABLES ""
set_interface_property mms SVD_ADDRESS_GROUP ""

add_interface_port mms MMS_write write Input 1
add_interface_port mms MMS_writedata writedata Input 32
add_interface_port mms MMS_readdata readdata Output 32
add_interface_port mms MMS_read read Input 1
add_interface_port mms MMS_addr address Input 2
set_interface_assignment mms embeddedsw.configuration.isFlash 0
set_interface_assignment mms embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mms embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mms embeddedsw.configuration.isPrintableDevice 0

